#!/usr/bin/env node

const { execSync } = require('child_process')
const fs = require('fs')
const path = require('path')
const prettier = require('prettier')
const handlebars = require('handlebars')
const { MOCK_DATA, PRINT_DATA_FOR } = require('./env')

const DIST_DIR = path.resolve('dist')

function renderTemplate(createTemplate, name) {
  let { template, templateText, mockData } = createTemplate()

  // Prettify templates
  template = prettier.format(template, { parser: 'html', printWidth: 999 })
  templateText = prettier.format(templateText, {
    parser: 'markdown',
    proseWrap: 'always',
    printWidth: 80,
  })

  // Remove extra whitespaces in the text template
  templateText = templateText.replace(/^ +/gm, '')

  if (MOCK_DATA) {
    template = handlebars.compile(template)(mockData)
    templateText = handlebars.compile(templateText)(mockData)
  }

  fs.mkdirSync(DIST_DIR, { recursive: true })
  fs.writeFileSync(path.join(DIST_DIR, name + '.html'), template, 'utf8')
  fs.writeFileSync(path.join(DIST_DIR, name + '.txt'), templateText, 'utf8')
}

function generateTemplates(files) {
  execSync(`rm -rf "${DIST_DIR}"`)

  files.forEach(filename => {
    const template = require(path.join(__dirname, 'templates', filename))
    renderTemplate(template, path.basename(filename, '.js'))
  })

  execSync(`cp -r "${__dirname}/assets" "${DIST_DIR}/assets"`)
}

function printTemplateData(files, filename) {
  // Tolerate .js suffix in the name passed to PRINT_DATA_FOR
  const name = path.basename(filename, '.js')

  const templateFile = files.find(filename => filename === name + '.js')

  if (!templateFile) {
    console.error(
      `Error: the template ${PRINT_DATA_FOR} couldn’t be found. ` +
        `Please check the PRINT_DATA_FOR variable.`
    )
    process.exit(1)
  }

  const createTemplate = require(path.join(
    __dirname,
    'templates',
    filename + '.js'
  ))
  const template = createTemplate()

  console.log('')
  console.log(`Data for the template “${name}”:`)
  console.log('')
  console.log(JSON.stringify(template.mockData, null, 2))
  console.log('')
}

function main() {
  const files = fs
    .readdirSync(path.join(__dirname, 'templates'))
    .filter(filename => filename.endsWith('.js'))

  // Print template data
  if (PRINT_DATA_FOR) {
    printTemplateData(files, PRINT_DATA_FOR)
    return
  }

  // Generate the templates
  generateTemplates(files)
}
main()
