#!/usr/bin/env node

const fs = require('fs')
const path = require('path')
const mjml2html = require('mjml')
const drafted = require('./templates/drafted')
const missedVote = require('./templates/missed-vote')
const emailVerification = require('./templates/email-verification')
const dueTasks = require('./templates/due-tasks')

const DIST_DIR = path.join(__dirname, 'dist')

function renderTemplate(template, filename) {
  const output = mjml2html(template(), { beautify: true })

  if (output.errors.length) {
    console.error(output.errors)
    process.exit(1)
  }

  fs.mkdirSync(DIST_DIR, { recursive: true })
  fs.writeFileSync(path.join(DIST_DIR, filename), output.html, 'utf8')
}

renderTemplate(drafted, 'drafted.html')
renderTemplate(missedVote, 'missed-vote.html')
renderTemplate(emailVerification, 'email-verification.html')
renderTemplate(dueTasks, 'due-tasks.html')
